// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAu-muyOGkPHIXlmqC1_Ezkm7Tl96oc0l4',
    appId: '1:315651652168:web:7365202f5271b2af01b67d',
    messagingSenderId: '315651652168',
    projectId: 'onlinechatapp-e1870',
    authDomain: 'onlinechatapp-e1870.firebaseapp.com',
    storageBucket: 'onlinechatapp-e1870.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_ehS1czA9uh-qJPsKpA5e67w1TwvKj_k',
    appId: '1:315651652168:android:e243aba00a74690601b67d',
    messagingSenderId: '315651652168',
    projectId: 'onlinechatapp-e1870',
    storageBucket: 'onlinechatapp-e1870.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAt0YQEA27spIftxUXNG_YqGsyc3LZN4ck',
    appId: '1:315651652168:ios:a9a5858988fb8d9b01b67d',
    messagingSenderId: '315651652168',
    projectId: 'onlinechatapp-e1870',
    storageBucket: 'onlinechatapp-e1870.appspot.com',
    androidClientId: '315651652168-5eu2umrpgufmr0m3dvm379lam7oleke2.apps.googleusercontent.com',
    iosClientId: '315651652168-ujdpjtjfm8c9joj4chj0jnkkn65523cv.apps.googleusercontent.com',
    iosBundleId: 'com.example.onlineChatapplication',
  );

}